"""create exchange rates table"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '24d71e4e04e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'base_currency', 'quote_currency', 'observed_at')
    )
    op.create_index(op.f('ix_exchange_rates_base_currency'), 'exchange_rates', ['base_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_observed_at'), 'exchange_rates', ['observed_at'], unique=False)
    op.create_index(op.f('ix_exchange_rates_quote_currency'), 'exchange_rates', ['quote_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_source'), 'exchange_rates', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_source'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_quote_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_observed_at'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_base_currency'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
